import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  ArrowLeft, ArrowRight, Check, ChevronRight, CircleHelp, Cloud, Crown, Flower2,
  Gift, Heart, KeyRound, LockKeyhole, Moon, Music2, Pause, Play, RotateCcw, Settings,
  Shirt, Sparkles, Star, Timer, Trophy, Volume2, VolumeX, Waves, X, Zap, Cat, CakeSlice,
  Dices, Gem, Camera, Coffee, Wand2, Shield, CircleDot, Palette, Scissors, Footprints,
  Droplets, Search, Eye, Flame, Rainbow, Disc3, Ticket, Lightbulb, Medal
} from 'lucide-react';
import './styles.css';

type ActivityId = 'anger'|'cafe'|'garden'|'cloud'|'cozy'|'arcade'|'dress'|'carnival'|'music'|'chocolate'|'pet'|'dance'|'mystery'|'compliment'|'button'|'quiz'|'castle'|'moon';
type Screen = ActivityId|'final'|null;
type Activity = {id:ActivityId; title:string; kicker:string; subtitle:string; collectible:string; theme:string; icon:React.ReactNode};
type State = {
  v:number; completed:ActivityId[]; collectibles:string[]; achievements:string[]; visited:ActivityId[];
  bonks:number; flowers:number; stars:number; cozyFound:number; arcade:number; outfit:string[];
  spins:number; music:number; chocolate:number; pet:number; dance:number; mystery:number;
  compliments:number; button:number; quiz:number; castle:number; moon:number; sound:boolean; reduced:boolean;
};
const CONFIG={HER_NAME:'Zainab',YOUR_NAME:'Me',NICKNAME:'',GREETING:'A private little universe, built from tiny games, soft chaos, and an unreasonable amount of effort.',FINAL_MESSAGE:[
  'You made it all the way here.', 'Every little thing you touched became part of this room.',
  'The stars you caught. The flowers you grew. The outfit you built. The ridiculous buttons you pressed.',
  'None of it was filler.', 'I wanted to make you a place where you could wander without having to explain anything.',
  'So this is yours.', 'Your tiny universe.', 'And yes, I really did build an entire universe just to steal a smile from you.'
]};
const A:Activity[]=[
{id:'anger',title:'The Anger Room',kicker:'01 · COMIC RELIEF',subtitle:'Bonk the responsible party with increasingly ridiculous objects.',collectible:'Impact Star',theme:'anger',icon:<Zap/>},
{id:'cafe',title:'Strawberry Café',kicker:'02 · PATISSERIE',subtitle:'Assemble the order in the exact sequence the tiny chef demands.',collectible:'Strawberry Charm',theme:'cafe',icon:<CakeSlice/>},
{id:'garden',title:'Cherry Blossom Garden',kicker:'03 · GARDEN',subtitle:'Plant five flowers, water them, and watch the garden wake up.',collectible:'Blossom',theme:'garden',icon:<Flower2/>},
{id:'cloud',title:'Cloud Kingdom',kicker:'04 · SKY',subtitle:'Chase the glowing star as it jumps around the clouds.',collectible:'Star Fragment',theme:'cloud',icon:<Cloud/>},
{id:'cozy',title:'The Cozy Room',kicker:'05 · HIDEAWAY',subtitle:'Find six little objects hiding in the lamplight.',collectible:'Firefly',theme:'cozy',icon:<Coffee/>},
{id:'arcade',title:'Neon Arcade',kicker:'06 · ARCADE',subtitle:'Hit the target before it teleports somewhere else.',collectible:'Arcade Token',theme:'arcade',icon:<CircleDot/>},
{id:'dress',title:'The Wardrobe',kicker:'07 · COUTURE',subtitle:'Build a complete look. The clothes actually appear on the character.',collectible:'Ribbon',theme:'dress',icon:<Shirt/>},
{id:'carnival',title:'Midnight Carnival',kicker:'08 · CARNIVAL',subtitle:'Spin three times and collect whatever fate hands you.',collectible:'Golden Ticket',theme:'carnival',icon:<Dices/>},
{id:'music',title:'Magic Music Box',kicker:'09 · SOUND',subtitle:'Listen to the melody and repeat the glowing sequence.',collectible:'Music Note',theme:'music',icon:<Music2/>},
{id:'chocolate',title:'Chocolate Atelier',kicker:'10 · CONFECTIONERY',subtitle:'Shape, coat, decorate, then send your masterpiece to quality control.',collectible:'Cocoa Gem',theme:'chocolate',icon:<Gem/>},
{id:'pet',title:'Tiny Pet Society',kicker:'11 · COMPANION',subtitle:'Care for a tiny creature until the trust meter reaches full.',collectible:'Pet Heart',theme:'pet',icon:<Cat/>},
{id:'dance',title:'The Spotlight',kicker:'12 · PERFORMANCE',subtitle:'Follow the choreography and make the stage react to every move.',collectible:'Spotlight',theme:'dance',icon:<Wand2/>},
{id:'mystery',title:'The Mystery House',kicker:'13 · PUZZLES',subtitle:'Solve four tiny mysteries to unlock the final key.',collectible:'Mystery Key',theme:'mystery',icon:<KeyRound/>},
{id:'compliment',title:'Compliment Laboratory',kicker:'14 · RESEARCH',subtitle:'Run three completely serious experiments in the science of you.',collectible:'Love Formula',theme:'compliment',icon:<Heart/>},
{id:'button',title:'The Forbidden Button',kicker:'15 · DO NOT',subtitle:'It says do not press it. Obviously that means press it.',collectible:'Warning Badge',theme:'button',icon:<Shield/>},
{id:'quiz',title:'The Extremely Official Quiz',kicker:'16 · CLASSIFIED',subtitle:'Answer three absurdly important questions. You may retry.',collectible:'Quiz Seal',theme:'quiz',icon:<CircleHelp/>},
{id:'castle',title:'Achievement Castle',kicker:'17 · ARCHIVE',subtitle:'Place five artifacts into the castle and watch the collection come alive.',collectible:'Crown Fragment',theme:'castle',icon:<Crown/>},
{id:'moon',title:'Moonlight Observatory',kicker:'18 · CONSTELLATION',subtitle:'Connect every glowing star in order. The sky is hiding something.',collectible:'Moonstone',theme:'moon',icon:<Moon/>}
];
const defaultState=():State=>({v:6,completed:[],collectibles:[],achievements:[],visited:[],bonks:0,flowers:0,stars:0,cozyFound:0,arcade:0,outfit:[],spins:0,music:0,chocolate:0,pet:0,dance:0,mystery:0,compliments:0,button:0,quiz:0,castle:0,moon:0,sound:true,reduced:false});
function load():State{try{const x=JSON.parse(localStorage.getItem('tiny-universe-v6')||'null');return x?.v===6?{...defaultState(),...x}:defaultState()}catch{return defaultState()}}
function uniq<T>(a:T[],x:T){return a.includes(x)?a:[...a,x]}
function complete(s:State,id:ActivityId,item:string):State{return {...s,completed:uniq(s.completed,id),collectibles:uniq(s.collectibles,item)}}
function pct(n:number,d:number){return Math.min(100,Math.round(n/d*100))}
function sfx(kind:'tap'|'good'|'soft'|'bad',enabled:boolean){if(!enabled)return;try{const C=window.AudioContext||(window as any).webkitAudioContext;if(!C)return;const c=new C(),now=c.currentTime;const seq=kind==='good'?[523.25,659.25,783.99]:kind==='soft'?[392,523.25]:kind==='bad'?[180,120]:[440];seq.forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.type=kind==='tap'?'sine':'triangle';o.frequency.value=f;g.gain.setValueAtTime(.0001,now+i*.07);g.gain.exponentialRampToValueAtTime(kind==='tap'?.025:.06,now+i*.07+.01);g.gain.exponentialRampToValueAtTime(.0001,now+i*.07+.18);o.connect(g).connect(c.destination);o.start(now+i*.07);o.stop(now+i*.07+.2)});setTimeout(()=>c.close().catch(()=>{}),500)}catch{}}
function usePersist(state:State){useEffect(()=>{localStorage.setItem('tiny-universe-v6',JSON.stringify(state))},[state])}
function Stars({n=36}:{n?:number}){return <div className="stars" aria-hidden>{Array.from({length:n},(_,i)=><i key={i} style={{left:`${(i*37.7)%100}%`,top:`${(i*61.3)%100}%`,animationDelay:`${(i%8)*.35}s`}}/>)}</div>}
function Character({outfit=[],mood='idle'}:{outfit?:string[];mood?:string}){return <div className={`char ${mood}`}><div className="char-shadow"/><div className="hair"/><div className="face"><i/><i/><b/></div><div className="neck"/><div className="shirt-base"/>{outfit.includes('Cloud Skirt')&&<div className="skirt"/>}{outfit.includes('Pearl Jacket')&&<div className="jacket"/>}{outfit.includes('Midnight Bow')&&<div className="bow">✦</div>}{outfit.includes('Star Glasses')&&<div className="glasses"><i/><i/></div>}{outfit.includes('Cherry Boots')&&<><div className="boot left"/><div className="boot right"/></>} {outfit.includes('Silver Crown')&&<div className="crown">♕</div>}<div className="arm left"/><div className="arm right"/><div className="leg left"/><div className="leg right"/></div>}
function Button({children,onClick,kind='primary',disabled=false}:{children:React.ReactNode;onClick?:()=>void;kind?:'primary'|'secondary'|'ghost'|'danger';disabled?:boolean}){return <button className={`btn ${kind}`} disabled={disabled} onClick={onClick}>{children}</button>}
function Room({a,state,setState,onBack,children}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void;children:React.ReactNode}){
 const done=state.completed.includes(a.id), idx=A.findIndex(x=>x.id===a.id), next=A[idx+1]; const [celebrate,setCelebrate]=useState(false); const seen=useRef(done);
 const finish=()=>setState(s=>complete(s,a.id,a.collectible));
 useEffect(()=>{if(done&&!seen.current){setCelebrate(true);sfx('good',state.sound)}seen.current=done},[done]);
 const goNext=()=>{setCelebrate(false);if(next)window.dispatchEvent(new CustomEvent('tu-next',{detail:next.id}));else onBack()};
 return <div className={`room theme-${a.theme}`}><Stars n={28}/><header className="room-head"><Button kind="ghost" onClick={()=>{sfx('soft',state.sound);onBack()}}><ArrowLeft/> Atlas</Button><div><span>{a.kicker}</span><h1>{a.title}</h1></div><div className="room-complete">{done?<><Check/> COMPLETE</>:'PLAYING'}</div></header><main className="room-main"><div className="room-intro"><p>{a.subtitle}</p><span><Sparkles/> {a.collectible}</span></div>{children}{!done&&<div className="safety"><small>Everything here is playable. Nothing is a dead end.</small><Button kind="secondary" onClick={finish}>Finish & collect <Check/></Button></div>}</main>{celebrate&&<div className="overlay"><div className="celebrate"><div className="burst">✦</div><span>WORLD COMPLETE</span><h2>{a.title}</h2><p><Sparkles/> {a.collectible} joined your collection.</p><div className="actions">{next?<Button onClick={goNext}>Next world <ArrowRight/></Button>:<Button onClick={goNext}>Return to atlas <ArrowLeft/></Button>}<Button kind="secondary" onClick={()=>setCelebrate(false)}>Stay here</Button></div></div></div>}</div>
}
function Progress({state}:{state:State}){return <div className="progress"><div className="ring" style={{'--p':`${pct(state.collectibles.length,18)}%`} as React.CSSProperties}/><b>{state.collectibles.length}</b><span>/18</span></div>}
function Bonk({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const [hits,setHits]=useState(0),[tool,setTool]=useState('Foam Hammer'),[pop,setPop]=useState(false);const tools=['Foam Hammer','Slipper','Teddy','Tomato','Confetti'];const hit=()=>{const n=hits+1;setHits(n);setPop(true);setTimeout(()=>setPop(false),180);setState(s=>{const x={...s,bonks:s.bonks+1};return n>=12?complete(x,a.id,a.collectible):x})};return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="bonk-grid"><div className={`bonk-stage ${pop?'shake':''}`}><div className="comic">BONK!</div><Character mood={pop?'bonked':'nervous'}/><div className="meter"><span>COMIC DAMAGE</span><b>{hits}/12</b><i><em style={{width:`${pct(hits,12)}%`}}/></i></div></div><div className="panel"><label>Choose your extremely serious instrument</label><div className="choice-grid">{tools.map(x=><button className={tool===x?'chosen':''} key={x} onClick={()=>{setTool(x);sfx('tap',state.sound)}}>{x}</button>)}</div><Button kind="danger" onClick={hit}>BONK WITH {tool.toUpperCase()} <Zap/></Button><p className="quip">{hits===0?'The helmet is mostly decorative.':hits<5?'That definitely made a sound.':hits<10?'The tiny universe is taking notes.':'The responsible party requests a lawyer.'}</p></div></div></Room>}
function Cafe({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const order=['Strawberry','Cloud Cream','Sprinkles','Vanilla'];const ing=['Strawberry','Cloud Cream','Sprinkles','Vanilla','Berry Jam','Moon Sugar'];const [picked,setPicked]=useState<string[]>([]);const add=(x:string)=>{if(picked.includes(x))return;if(x!==order[picked.length]){sfx('bad',state.sound);return}const n=[...picked,x];setPicked(n);sfx('tap',state.sound);if(n.length===order.length)setState(s=>complete({...s,cafe:1 as any},a.id,a.collectible))};return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="cafe-grid"><div className="cafe-art"><div className="awning">STRAWBERRY CAFÉ</div><div className="cake"><span>✦</span><i/><i/><i/></div><div className="steam">☁　☁　☁</div></div><div className="panel recipe"><span>ORDER #07</span><h2>Pink Cloud</h2><div className="steps">{order.map((x,i)=><div className={picked[i]===x?'done':''} key={x}><b>0{i+1}</b>{x}{picked[i]===x&&<Check/>}</div>)}</div><div className="choice-grid">{ing.map(x=><button key={x} className={picked.includes(x)?'chosen':''} disabled={picked.includes(x)} onClick={()=>add(x)}>{x}</button>)}</div><small>Wrong ingredient? It politely refuses.</small></div></div></Room>}
function Garden({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const [selected,setSelected]=useState<number|null>(null);const [water,setWater]=useState(0);const grow=()=>{if(selected===null)return;const w=water+1;setWater(w);sfx('soft',state.sound);if(w>=3){const flowers=Math.min(5,state.flowers+1);setWater(0);setState(s=>{const x={...s,flowers};return flowers>=5?complete(x,a.id,a.collectible):x})}};return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="garden"><div className="garden-sky"><div className="sun"/><div className="mountain one"/><div className="mountain two"/><div className="petal-stream">✿　✧　✿　·　✧　✿</div></div><div className="soil">{Array.from({length:5},(_,i)=><button key={i} className={`flower ${state.flowers>i?'grown':''} ${selected===i?'selected':''}`} style={{left:`${10+i*19}%`}} onClick={()=>{setSelected(i);setWater(0)}}><span className="stem"/><span className="head">✿</span><small>{state.flowers>i?'grown':'seed'}</small></button>)}</div><div className="garden-bar"><b>{state.flowers}/5 flowers</b><span>{selected===null?'Choose a patch':`Patch ${selected+1} · water ${water}/3`}</span><Button onClick={grow} disabled={selected===null}>Water <Droplets/></Button></div></div></Room>}
function Cloud({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const [run,setRun]=useState(false),[score,setScore]=useState(0),[time,setTime]=useState(18),[target,setTarget]=useState(0);const ref=useRef<number | null>(null);useEffect(()=>()=>ref.current&&clearInterval(ref.current),[]);const start=()=>{setRun(true);setScore(0);setTime(18);setTarget(0);ref.current=window.setInterval(()=>setTime(t=>{if(t<=1){if(ref.current)clearInterval(ref.current);setRun(false);return 0}return t-1}),1000)};useEffect(()=>{if(!run&&score>=10)setState(s=>complete({...s,stars:Math.max(s.stars,score)},a.id,a.collectible))},[run,score]);const catchStar=()=>{if(!run)return;setScore(x=>x+1);setTarget(x=>(x+1)%9);sfx('tap',state.sound)};return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="cloud"><div className="cloud-top"><span><Star/> {score}</span><span><Timer/> {time}s</span></div><div className="cloud-arena">{Array.from({length:9},(_,i)=><button key={i} className={target===i?'star-target':''} style={{left:`${8+(i*31)%82}%`,top:`${12+(i*47)%72}%`}} onClick={catchStar}><Star fill="currentColor"/></button>)}<div className="cloud-puff one"/><div className="cloud-puff two"/></div><Button onClick={start}>{run?'CATCH!':'START STARFALL'} <Star/></Button><small>Catch 10 glowing stars before the clock reaches zero.</small></div></Room>}
function Cozy({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const items=['lamp','book','mug','cat','key','letter'];const [found,setFound]=useState<number[]>([]);const click=(i:number)=>{const n=uniq(found,i);setFound(n);if(n.length>=6)setState(s=>complete({...s,cozyFound:6},a.id,a.collectible));sfx('tap',state.sound)};return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="cozy"><div className="window"><div className="moon-orb"/><span>2:17 AM</span></div><div className="sofa"/><div className="table"/><div className="lamp"/>{items.map((x,i)=><button key={x} className={`hidden ${x} ${found.includes(i)?'found':''}`} onClick={()=>click(i)}>{found.includes(i)?<Check/>:x==='cat'?<Cat/>:<Search/>}</button>)}<div className="cozy-note">{found.length}/6 found · {found.length===6?'The room approves.':'The quiet things are hiding.'}</div></div></Room>}
function Arcade({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const [run,setRun]=useState(false),[score,setScore]=useState(0),[time,setTime]=useState(15),[target,setTarget]=useState(0);const ref=useRef<number | null>(null);useEffect(()=>()=>ref.current&&clearInterval(ref.current),[]);const start=()=>{setRun(true);setScore(0);setTime(15);setTarget(0);ref.current=window.setInterval(()=>setTime(t=>{if(t<=1){if(ref.current)clearInterval(ref.current);setRun(false);return 0}return t-1}),1000)};useEffect(()=>{if(!run&&score>=12)setState(s=>complete({...s,arcade:Math.max(s.arcade,score)},a.id,a.collectible))},[run,score]);return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="arcade"><div className="arcade-screen"><span className="arcade-score">{String(score).padStart(2,'0')}</span><span className="arcade-time">{time}</span>{run?<button className="arcade-target" style={{left:`${10+(target*37)%78}%`,top:`${14+(target*53)%70}%`}} onClick={()=>{setScore(x=>x+1);setTarget(x=>x+1);sfx('tap',state.sound)}}><CircleDot/></button>:<div className="insert">INSERT COURAGE</div>}</div><div className="arcade-controls"><Button onClick={start}>{run?'RESTART':'START GAME'} <Zap/></Button><div><b>12</b><span>hits to win</span></div><div><b>0</b><span>mercy</span></div></div></div></Room>}
function Dress({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const pieces=['Pearl Jacket','Midnight Bow','Cherry Boots','Star Glasses','Cloud Skirt','Silver Crown'];const toggle=(x:string)=>setState(s=>({...s,outfit:s.outfit.includes(x)?s.outfit.filter(y=>y!==x):[...s.outfit,x]}));return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="dress"><div className="runway"><div className="curtain left"/><div className="curtain right"/><div className="spotlight"/><Character outfit={state.outfit} mood="fashion"/><div className="look-tag">LOOK {String(state.outfit.length).padStart(2,'0')}</div></div><div className="wardrobe panel"><div className="wardrobe-head"><span>WARDROBE</span><b>{state.outfit.length}/6 pieces</b></div>{pieces.map(x=><button key={x} className={state.outfit.includes(x)?'chosen':''} onClick={()=>{toggle(x);sfx('tap',state.sound)}}>{state.outfit.includes(x)?<Check/>:<Shirt/>}{x}</button>)}<small>Watch the character change as you dress her.</small></div></div></Room>}
function Carnival({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const prizes=['Tiny hug','Golden star','Cake','Applause','Bonus ticket','Mystery prize'];const [spin,setSpin]=useState(false),[result,setResult]=useState('');const go=()=>{if(spin)return;setSpin(true);setTimeout(()=>{const r=prizes[Math.floor(Math.random()*prizes.length)];setResult(r);setSpin(false);setState(s=>{const spins=s.spins+1;return spins>=3?complete({...s,spins},a.id,a.collectible):{...s,spins}});sfx('good',state.sound)},850)};return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="carnival"><div className={`wheel ${spin?'spinning':''}`}>{prizes.map((p,i)=><span key={p} style={{transform:`rotate(${i*60}deg) translateY(-110px)`}}>{i+1}</span>)}<div className="wheel-core">★</div></div><div className="pointer">▼</div><div className="carnival-copy"><span>SPINS {state.spins}/3</span><h2>{result||'The wheel knows nothing and yet acts confident.'}</h2><Button onClick={go}>SPIN <Dices/></Button></div></div></Room>}
function Music({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const notes=['C','E','G','A','B','G'];const [seq,setSeq]=useState<number[]>([]),[input,setInput]=useState<number[]>([]),[playing,setPlaying]=useState(false),[ready,setReady]=useState(false);const newSeq=()=>{const n=Array.from({length:6},()=>Math.floor(Math.random()*6));setSeq(n);setInput([]);setReady(true);setPlaying(true);n.forEach((v,i)=>setTimeout(()=>sfx('tap',state.sound),i*280));setTimeout(()=>setPlaying(false),1700)};const tap=(i:number)=>{if(playing||!ready)return;const n=[...input,i];setInput(n);if(i!==seq[n.length-1]){sfx('bad',state.sound);setInput([]);return}if(n.length===seq.length){setState(s=>complete({...s,music:6},a.id,a.collectible));setReady(false);sfx('good',state.sound)}};return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="music"><div className="music-orbit"><div className="music-core"><Music2/></div>{notes.map((x,i)=><button key={i} className={input.includes(i)?'lit':''} onClick={()=>tap(i)}>{x}</button>)}</div><div className="music-console"><Button onClick={newSeq}>{playing?'LISTENING...':'PLAY A MELODY'} <Play/></Button><div className="note-seq">{seq.map((x,i)=><span key={i} className={i<input.length?'hit':''}>{notes[x]}</span>)}</div><small>Listen first. Then repeat the glowing notes.</small></div></div></Room>}
function Chocolate({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const [shape,setShape]=useState('Moon'),[coat,setCoat]=useState('Ruby'),[decor,setDecor]=useState('Star');const finish=()=>setState(s=>complete({...s,chocolate:1},a.id,a.collectible));return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="choco"><div className="choco-preview"><div className={`chocopiece ${shape.toLowerCase()}`} data-coat={coat}>{decor==='Star'?'★':decor==='Heart'?'♥':'✦'}</div><div className="belt"/></div><div className="panel"><span>ATELIER / SIGNATURE</span><h2>Build the piece.</h2>{[['SHAPE',['Moon','Heart','Square'],shape,setShape],['COATING',['Ruby','Dark','Vanilla'],coat,setCoat],['DECOR',['Star','Heart','Spark'],decor,setDecor]].map(([label,vals,val,set] : any)=><div className="control" key={label as string}><small>{label as string}</small><div>{(vals as string[]).map(x=><button className={val===x?'chosen':''} key={x} onClick={()=>set(x)}>{x}</button>)}</div></div>)}<Button onClick={finish}>QUALITY CONTROL <Check/></Button></div></div></Room>}
function Pet({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const acts=['PET','TREAT','BRUSH','TOY'];const [mood,setMood]=useState('idle');const care=(x:string)=>{setMood(x.toLowerCase());setState(s=>{const pet=Math.min(6,s.pet+1);return pet>=6?complete({...s,pet},a.id,a.collectible):{...s,pet}});sfx('soft',state.sound)};return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="pet"><div className="pet-scene"><div className="pet-glow"/><div className={`pet-emoji ${mood}`}><Cat/></div><div className="pet-name">MISO</div><span>{state.pet<6?'Miso is waiting.':'Miso has officially adopted you.'}</span></div><div className="panel pet-panel"><div className="trust"><span>TRUST</span><b>{state.pet}/6</b><i><em style={{width:`${pct(state.pet,6)}%`}}/></i></div><div className="care-grid">{acts.map(x=><button key={x} onClick={()=>care(x)}>{x}</button>)}</div></div></div></Room>}
function Dance({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const pads=['←','↑','↓','→'];const [pattern,setPattern]=useState([0,1,3,2,1,0]),[step,setStep]=useState(0),[score,setScore]=useState(0);const hit=(i:number)=>{if(i===pattern[step]){const s=score+10;setScore(s);if(step===pattern.length-1){setState(x=>complete({...x,dance:Math.max(x.dance,s)},a.id,a.collectible));setStep(0);setScore(0);sfx('good',state.sound)}else setStep(x=>x+1);sfx('tap',state.sound)}else{sfx('bad',state.sound);setScore(x=>Math.max(0,x-3))}};return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="dance"><div className="stage"><div className="disco"/><Character mood={step%2?'dance':'proud'}/><div className="score">SCORE {score}</div></div><div className="dance-console"><div className="choreo">{pattern.map((p,i)=><span key={i} className={i===step?'current':i<step?'hit':''}>{pads[p]}</span>)}</div><div className="pads">{pads.map((x,i)=><button key={x} onClick={()=>hit(i)}>{x}</button>)}</div><small>Hit the glowing step. Finish the six-beat sequence.</small></div></div></Room>}
function Mystery({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const qs=[['I have hands but cannot clap. What am I?','clock'],['What has keys but opens no doors?','piano'],['I get wetter the more I dry. What am I?','towel'],['What has one eye but cannot see?','needle']];const [i,setI]=useState(0),[answer,setAnswer]=useState(''),[msg,setMsg]=useState('');const submit=()=>{if(answer.trim().toLowerCase()===qs[i][1]){sfx('good',state.sound);if(i===qs.length-1)setState(s=>complete({...s,mystery:4},a.id,a.collectible));else{setI(i+1);setAnswer('');setMsg('Correct. The next lock clicks open.')}}else{setMsg('Not quite. Try again.');sfx('bad',state.sound)}};return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="mystery"><div className="door"><div className="lock"><LockKeyhole/></div><div className="clue-number">LOCK {i+1}/4</div><h2>{qs[i][0]}</h2></div><div className="panel mystery-panel"><div className="lock-dots">{qs.map((_,n)=><i key={n} className={n<i?'done':n===i?'current':''}/>)}</div><input value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} placeholder="Type your answer..."/><Button onClick={submit}>UNLOCK <KeyRound/></Button><p>{msg}</p></div></div></Room>}
function Compliment({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const lines=['Your smile has catastrophic levels of power.','You make ordinary moments feel expensive.','A tiny universe would absolutely choose you as its main character.','Your unimpressed face deserves its own museum.','You somehow make quiet feel comfortable.','You are very, very easy to root for.'];const [cards,setCards]=useState<string[]>([]);const run=()=>{const x=lines[(cards.length*2+Math.floor(Math.random()*lines.length))%lines.length];setCards(c=>[...c,x]);setState(s=>{const compliments=s.compliments+1;return compliments>=3?complete({...s,compliments},a.id,a.collectible):{...s,compliments}});sfx('good',state.sound)};return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="lab"><div className="scanner"><div className="scanline"/><div className="scan-orb"><Heart/></div><span>SUBJECT: {CONFIG.HER_NAME.toUpperCase()}</span><b>RESULT: RIDICULOUSLY LOVABLE</b></div><div className="panel"><span>EXPERIMENT {Math.min(3,cards.length+1)}/3</span><h2>Run the compliment machine.</h2><Button onClick={run}>GENERATE <Sparkles/></Button><div className="compliment-cards">{cards.map((x,i)=><article key={i}><Heart/> {x}</article>)}</div></div></div></Room>}
function Forbidden({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const press=()=>{setState(s=>{const button=s.button+1;return button>=15?complete({...s,button},a.id,a.collectible):{...s,button}});sfx(state.button%5===4?'bad':'tap',state.sound)};return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="forbidden"><div className={`forbidden-core ${state.button%2?'pulse':''}`}><div className="warning">DO NOT</div><button onClick={press}>PRESS<br/>ME</button><div className="counter">{String(state.button).padStart(2,'0')} / 15</div></div><div className="panel"><span>THE FORBIDDEN BUTTON</span><h2>{state.button<5?'This is a terrible idea.':state.button<10?'You are still doing it.':state.button<15?'The button is becoming nervous.':'The button has accepted its fate.'}</h2><small>Every press changes the room.</small></div></div></Room>}
function Quiz({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const qs=[['What color is the moon in this universe?',['Lavender','Orange','Green'],0],['Which creature runs the Cozy Room?',['A cat','A dragon','A very tired penguin'],0],['What happens when you press the forbidden button?',['Absolutely nothing','Something suspicious','It apologizes'],1]] as const;const [i,setI]=useState(0),[score,setScore]=useState(0);const answer=(n:number)=>{const s=score+(n===qs[i][2]?1:0);if(n===qs[i][2])sfx('good',state.sound);else sfx('bad',state.sound);if(i===qs.length-1)setState(x=>complete({...x,quiz:Math.max(x.quiz,s)},a.id,a.collectible));else{setScore(s);setI(i+1)}};return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="quiz"><div className="quiz-card"><span>QUESTION {i+1}/3</span><h2>{qs[i][0]}</h2><div>{qs[i][1].map((x,n)=><button key={x} onClick={()=>answer(n)}>{x}</button>)}</div></div><div className="quiz-orbit"><CircleHelp/><b>Totally official.</b></div></div></Room>}
function Castle({a,state,setState,onBack}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void}){const [placed,setPlaced]=useState<number[]>([]);const items=['STAR','FLOWER','RIBBON','TICKET','GEM'];const place=(i:number)=>{if(placed.includes(i))return;const n=[...placed,i];setPlaced(n);if(n.length===5)setState(s=>complete({...s,castle:5},a.id,a.collectible));};return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="castle"><div className="castle-scene"><div className="castle-tower one"/><div className="castle-tower two"/><div className="castle-main"><Crown/></div><div className="banner">ARCHIVE OF LITTLE THINGS</div>{placed.map(i=><span key={i} className={`placed p${i}`}>{['★','✿','✦','🎟','◆'][i]}</span>)}</div><div className="panel archive"><span>FIVE ARTIFACTS</span><h2>Place them in the castle.</h2><div className="artifact-buttons">{items.map((x,i)=><button key={x} className={placed.includes(i)?'chosen':''} onClick={()=>place(i)}>{placed.includes(i)?<Check/>:['★','✿','✦','🎟','◆'][i]} {x}</button>)}</div><small>The castle remembers every piece you brought here.</small></div></div></Room>}
function Moon({a,state,setState,onBack,onFinal}:{a:Activity;state:State;setState:React.Dispatch<React.SetStateAction<State>>;onBack:()=>void;onFinal:()=>void}){const [next,setNext]=useState(0),[connected,setConnected]=useState<number[]>([]);const points=Array.from({length:8},(_,i)=>({x:12+(i*29)%76,y:18+(i*41)%66}));const tap=(i:number)=>{if(i!==next)return;sfx('tap',state.sound);const n=[...connected,i];setConnected(n);if(n.length===8){setState(s=>complete({...s,moon:8},a.id,a.collectible));setTimeout(()=>{if(state.completed.length>=17)onFinal()},700)}else setNext(i+1)};const all=state.completed.length>=17;return <Room a={a} state={state} setState={setState} onBack={onBack}><div className="moon"><div className="observatory"><div className="moon-disc"/><svg viewBox="0 0 100 100" className="constellation-lines">{connected.slice(1).map((v,i)=>{const p1=points[connected[i]],p2=points[v];return <line key={i} x1={p1.x} y1={p1.y} x2={p2.x} y2={p2.y}/>})}</svg>{points.map((p,i)=><button key={i} className={connected.includes(i)?'connected':''} style={{left:`${p.x}%`,top:`${p.y}%`}} onClick={()=>tap(i)}><Star fill="currentColor"/></button>)}<div className="observatory-label">STAR {Math.min(8,next)}/8</div></div><div className="panel"><span>THE LAST CONSTELLATION</span><h2>{all?'The sky is ready.':'Connect every star in order.'}</h2><p>{all?'Your tiny universe is opening its hidden door.':'Follow the numbered glow. There is no timer.'}</p></div></div></Room>}
function Final({state,onBack}:{state:State;onBack:()=>void}){const [n,setN]=useState(0);useEffect(()=>{if(n<CONFIG.FINAL_MESSAGE.length){const t=setTimeout(()=>setN(x=>x+1),n===0?700:1200);return()=>clearTimeout(t)}},[n]);return <div className="final"><Stars n={70}/><div className="aurora"/><div className="final-ring"/><div className="final-artifacts">{state.collectibles.map((x,i)=><span key={x} style={{transform:`rotate(${i*20}deg) translateY(-34vw) rotate(-${i*20}deg)`}}>✦</span>)}</div><div className="final-center"><div className="final-crown"><Crown/></div><div className="final-chars"><Character mood="soft"/><Character outfit={state.outfit} mood="soft"/></div><span>THE PLACE BEHIND THE STARS</span>{CONFIG.FINAL_MESSAGE.slice(0,n).map((x,i)=><p key={i} className={i===CONFIG.FINAL_MESSAGE.length-1?'big':''}>{x.replaceAll('[HER_NAME]',CONFIG.HER_NAME)}</p>)}{n>=CONFIG.FINAL_MESSAGE.length&&<><div className="final-badge"><Trophy/><small>ACHIEVEMENT UNLOCKED</small><b>Luckiest Girl in This Tiny Universe</b></div><Button kind="secondary" onClick={onBack}>Back to the universe <ArrowLeft/></Button></>}</div></div>}
function Home({state,setState,setScreen,onSettings}:{state:State;setState:React.Dispatch<React.SetStateAction<State>>;setScreen:(s:Screen)=>void;onSettings:()=>void}){const final=state.completed.length===18;return <div className={`home ${state.reduced?'reduced':''}`}><Stars/><div className="aurora a1"/><div className="aurora a2"/><header className="nav"><div className="brand">✦ A LITTLE UNIVERSE</div><div className="nav-tools"><span><Sparkles/> {state.collectibles.length}/18</span><Progress state={state}/><Button kind="ghost" onClick={onSettings}><Settings/></Button></div></header><main className="home-main"><section className="hero"><div className="hero-copy"><span>PRIVATE WORLD · FOR {CONFIG.HER_NAME.toUpperCase()}</span><h1>Somewhere between<br/><em>magic</em> and mischief.</h1><p>{CONFIG.GREETING}</p><div className="hero-actions"><Button onClick={()=>setScreen('anger')}>ENTER THE UNIVERSE <ArrowRight/></Button><small>{state.completed.length}/18 worlds completed</small></div></div><div className="hero-art"><div className="planet"/><div className="planet-ring"/><div className="float-card one"><Star/>18<small>tiny worlds</small></div><div className="float-card two"><Heart/>{state.achievements.length}<small>achievements</small></div><div className="hero-chars"><Character mood="proud"/><Character outfit={state.outfit} mood="soft"/></div></div></section><section className="atlas-head"><div><span>THE ATLAS</span><h2>Choose a destination.</h2><p>Everything is open. The secret is what happens after everything is complete.</p></div><div className="stats"><div><b>{state.completed.length}</b><small>COMPLETED</small></div><div><b>{state.collectibles.length}</b><small>ARTIFACTS</small></div><div><b>{state.achievements.length}</b><small>ACHIEVEMENTS</small></div></div></section><section className="atlas">{A.map((a,i)=><button key={a.id} className={`atlas-card ${a.theme} ${state.completed.includes(a.id)?'done':''}`} onClick={()=>setScreen(a.id)}><span className="num">{String(i+1).padStart(2,'0')}</span><div className="atlas-icon">{a.icon}</div><div><span>{a.kicker}</span><h3>{a.title}</h3><p>{a.subtitle}</p></div><ChevronRight className="arrow"/>{state.completed.includes(a.id)&&<div className="check"><Check/></div>}</button>)}{final&&<button className="secret-door" onClick={()=>setScreen('final')}><div>✦　·　★　·　✧　·　★　·　✦</div><Sparkles/><span>HIDDEN DESTINATION</span><h3>The Room Behind the Stars</h3><p>You completed every world. Now look what they made together.</p><ChevronRight/></button>}</section></main><footer>MADE FOR {CONFIG.HER_NAME.toUpperCase()} · WITH AN UNREASONABLE AMOUNT OF EFFORT · PROGRESS SAVED LOCALLY</footer></div>}
function App(){const [state,setState]=useState<State>(load);const [screen,setScreen]=useState<Screen>(null);const [settings,setSettings]=useState(false);usePersist(state);const activity=useMemo(()=>A.find(x=>x.id===screen),[screen]);useEffect(()=>{const next=(e:Event)=>setScreen((e as CustomEvent).detail);window.addEventListener('tu-next',next);return()=>window.removeEventListener('tu-next',next)},[]);useEffect(()=>{setState(s=>{let x=[...s.achievements];const add=(v:string)=>{if(!x.includes(v))x.push(v)};if(s.bonks>=12)add('Comic Menace');if(s.flowers>=5)add('Garden Architect');if(s.stars>=10)add('Star Catcher');if(s.outfit.length>=3)add('Fashion Director');if(s.pet>=6)add('Certified Softie');if(s.mystery>=4)add('Tiny Detective');if(s.button>=15)add('Button Criminal');if(s.completed.length>=12)add('Collector');if(s.completed.length===18)add('World Explorer');return x.length===s.achievements.length?s:{...s,achievements:x}})},[state.bonks,state.flowers,state.stars,state.outfit.length,state.pet,state.mystery,state.button,state.completed.length]);
 const common={state,setState,onBack:()=>setScreen(null)};if(screen==='final')return <Final state={state} onBack={()=>setScreen(null)}/>;if(activity){if(screen==='anger')return <Bonk a={activity} {...common}/>;if(screen==='cafe')return <Cafe a={activity} {...common}/>;if(screen==='garden')return <Garden a={activity} {...common}/>;if(screen==='cloud')return <Cloud a={activity} {...common}/>;if(screen==='cozy')return <Cozy a={activity} {...common}/>;if(screen==='arcade')return <Arcade a={activity} {...common}/>;if(screen==='dress')return <Dress a={activity} {...common}/>;if(screen==='carnival')return <Carnival a={activity} {...common}/>;if(screen==='music')return <Music a={activity} {...common}/>;if(screen==='chocolate')return <Chocolate a={activity} {...common}/>;if(screen==='pet')return <Pet a={activity} {...common}/>;if(screen==='dance')return <Dance a={activity} {...common}/>;if(screen==='mystery')return <Mystery a={activity} {...common}/>;if(screen==='compliment')return <Compliment a={activity} {...common}/>;if(screen==='button')return <Forbidden a={activity} {...common}/>;if(screen==='quiz')return <Quiz a={activity} {...common}/>;if(screen==='castle')return <Castle a={activity} {...common}/>;if(screen==='moon')return <Moon a={activity} {...common} onFinal={()=>setScreen('final')}/>}
 return <><Home state={state} setState={setState} setScreen={setScreen} onSettings={()=>setSettings(true)}/>{settings&&<div className="modal" onClick={()=>setSettings(false)}><div className="settings" onClick={e=>e.stopPropagation()}><Button kind="ghost" onClick={()=>setSettings(false)}><X/></Button><span>CONTROL ROOM</span><h2>Universe settings</h2><label><b>Sound effects</b><button onClick={()=>setState(s=>({...s,sound:!s.sound}))}>{state.sound?<Volume2/>:<VolumeX/>}</button></label><label><b>Reduced motion</b><button onClick={()=>setState(s=>({...s,reduced:!s.reduced}))}>{state.reduced?<Check/>:<CircleDot/>}</button></label><Button kind="danger" onClick={()=>{if(confirm('Reset the whole universe?'))setState(defaultState())}}><RotateCcw/> Reset progress</Button></div></div>}</>}
createRoot(document.getElementById('root')!).render(<App/>);
